-- 코드를 입력하세요
SELECT B.ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS B
INNER JOIN (SELECT ANIMAL_ID, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE SEX_UPON_INTAKE LIKE '%Intact%') A ON B.ANIMAL_ID = A.ANIMAL_ID
WHERE SEX_UPON_OUTCOME LIKE '%Spayed%'
OR SEX_UPON_OUTCOME LIKE '%Neutered%'
ORDER BY B.ANIMAL_ID ASC;




## 중성화가 되지않은 동물을  OUTS 에 조인해서 조인된 칼럼에 대해서 