SELECT YEAR(B.SALES_DATE) AS YEAR, 
       MONTH(B.SALES_DATE) AS MONTH, 
       A.GENDER, 
       COUNT(DISTINCT(A.USER_ID)) AS USERS
FROM ONLINE_SALE B
LEFT JOIN USER_INFO A ON A.USER_ID = B.USER_ID
WHERE !ISNULL(A.GENDER)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
