SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW D 
INNER JOIN (SELECT A.MEMBER_ID, A.MEMBER_NAME, B.REVIEW AS MAXMAN
FROM MEMBER_PROFILE A
JOIN (
SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW
FROM REST_REVIEW
GROUP BY MEMBER_ID
) B ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY B.REVIEW DESC
LIMIT 1) C ON D.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;