-- 코드를 작성해주세요
SELECT d.DEPT_ID, d.DEPT_NAME_EN, B.AVG_SAL 
FROM HR_DEPARTMENT d
JOIN (
    SELECT e.DEPT_ID, ROUND(AVG(e.SAL),0) AS AVG_SAL
    FROM HR_EMPLOYEES e 
    GROUP BY DEPT_ID
) B
ON d.DEPT_ID = B.DEPT_ID
GROUP BY d.DEPT_ID, d.DEPT_NAME_EN
ORDER BY AVG_SAL DESC;