SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME,
           RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RK
    FROM FOOD_PRODUCT
) AS ranked_products
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') AND RK = 1
ORDER BY MAX_PRICE DESC;